version: "3.9"

services:
  api:
    image: node:20-alpine
    working_dir: /workspace
    command: >-
      sh -c "pnpm install --frozen-lockfile && pnpm --filter api prisma migrate deploy && pnpm --filter api dev"
    env_file:
      - ../.env
    environment:
      DATABASE_URL: "file:/workspace/data/audit.db"
    volumes:
      - ..:/workspace
      - audit-data:/workspace/data
    ports:
      - "3000:3000"

volumes:
  audit-data:
